services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - hf_cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  hf_cache: