name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ secrets.HF_REPO }}
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"
          git remote add space https://huggingface.co/spaces/$HF_REPO
          git push --force https://username:$HF_TOKEN@huggingface.co/spaces/$HF_REPO main
