name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry & pre-commit
        run: |
          python -m pip install
          pip install poetry

      - name: Configure Poetry (no venv)
        run: poetry config virtualenvs.create false

      - name: Install deps
        run: poetry install --no-root

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run pytest
        run: poetry run pytest -q